name: Periodic Health Check

#on:
#  push:
#    branches:
#      - main

on:
  schedule:
    - cron: '00 12 * * *'  # Runs at 12:00 PM UTC every day

jobs:
    periodic_health_check_job:
        runs-on: ubuntu-latest
        steps:
          - name: Check the deployed service URL
            uses: jtalk/url-health-check-action@v4
            with:
                url: https://example.com|http://example.com
                max-attempts: 3 
                retry-delay: 20s