name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"

  print_date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Now it is
        run: date

  list_current_directory_job:
    runs-on: ubuntu-latest
    steps:
      - name: Directory content
        run: ls -l 