name: Deployment pipeline

on:
  push:
    branches: 
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP: ${{ contains(join(github.event.head_commit.message), '#skip') }}


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - if: ${{ env.SKIP != 'true' && github.event_name == 'push' && !cancelled() }}
        name: Trigger deployment on Render.com
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Discord Notification Success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() && env.SKIP != 'true' && github.event_name == 'push' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: 'Build Successful and Deployed on Render :white_check_mark:'
          description: 'Test discord notification success'

      - name: Discord Notification Failure
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() && env.SKIP != 'true' && github.event_name == 'push' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: 'Build Failed :x: '
          description: 'commit https://github.com/${{ github.repository }}/commit/${{ github.sha }} failed to deploy.'


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && needs.simple_deployment_pipeline.result == 'success' && env.SKIP != 'true' }}
        uses: anothrNick/github-tag-action@1.75.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: false
          DEFAULT_BUMP: patch
        

   